### ISSUE TITLE
Adding Django Unit Tests

### ISSUE THREAD

**Issue by listeph** [listeph/ratemylandlord#26]
- [documentation on how to write Django unit tests (written in `tests.py`)](https://docs.djangoproject.com/en/2.1/topics/testing/overview/)
- can set up CI for the unit tests from [Github actions](https://github.com/listeph/ratemylandlord/actions/new)

**Comment by Antsthebul** [comment]
Mind if I give it a shot

**Comment by listeph** [comment]
> Mind if I give it a shot

Sure! I might also work on it simultaneously later in the week though if you don't mind, because this repo is for a class project with our final deliverable due Fri.
