### ISSUE TITLE
Errors with ratemylandlord

### ISSUE THREAD

**Issue by mackstey28** [listeph/ratemylandlord#35]
Hey, noticed a couple issues while writing test cases:
- We can input duplicate landlords
- We can input landlords with invalid names
- When you lookup a landlord, it does not display the average score
- Add ability to add a written review?

**Comment by listeph** [comment]
This makes more sense as 3 separate issues with more descriptive titles. The first two can be grouped as "Add Landlord Form Validation" for example.
